### ISSUE TITLE
kci-dev development for milestone 8

### ISSUE THREAD

**Issue by nuclearcat** [kernelci/kci-dev#33]
This issue opened to track changes i planned for kci-dev tool.

## Changes

- [ ] Add a --test option to match test and return corresponding code to shell
- [ ] Add bisect subcommand that will use checkout subcommand and git bisect to find the commit that introduced a bug
- [ ] Add a patch(?) subcommand that will test pending patch or patches on specific tree, including storing these patches in kernelci storage system

**Comment by aliceinwire** [comment]
the patch sub-command should probably upgrade on this https://github.com/kernelci/kci-dev/blob/main/kci-dev/subcommands/patch.py

**Comment by nuclearcat** [comment]
Yes, definitely! I will edit main post for more correct explanation.

**Comment by aliceinwire** [comment]
by the way what milestone are you referring to ?

**Comment by nuclearcat** [comment]
We will discuss this weekly, and publish it at next public weekly. I and other team members defining tasks/topics what we would like to work on next 4 weeks from October 21st to November 17th. This will help to understand what features might appear sooner, where we must avoid blocking each other and etc.
And of course anybody who want to contribute/join efforts are welcome.

**Comment by aliceinwire** [comment]
are you telling me that this "milestone 8" is based on some collabora internal weekly meeting that will become public in next weeks?

**Comment by nuclearcat** [comment]
Correct.
